site_name: Process PI
site_url: https://processpi.org
repo_url: https://github.com/varma666/ProcessPi
repo_name: GitHub

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - toc.integrate
    - content.tabs.link
    - content.code.copy   # keep this
    # - content.action.edit  # remove this
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Install:
      - Installation: installation.md
  - User Guide:
      - Introduction: user-guide/introduction.md
      - Features: user-guide/features.md
      - Examples: user-guide/examples.md
      - Units:
          - Length: user-guide/units/length.md
          - Pressure: user-guide/units/pressure.md
          - Temperature: user-guide/units/temperature.md
  - API:
      - Overview: api_reference.md
      - Pipelines: user-guide/pipe-lines/pipelines.md
      - Heat Transfer: user-guide/calculations/calculations.md
      - Components: user-guide/components/components.md
  - Examples:
      - Pipeline Example: examples/pipeline-example.md
      - Heat Flux Example: examples/heatflux-example.md
      - Pump Example: examples/pump-example.md
  - Community:
      - Roadmap: about/roadmap.md
      - Contributing: about/contributing.md
      - License: about/license.md
      - Changelog: about/changelog.md
  - GitHub: https://github.com/varma666/ProcessPi
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/varma666/ProcessPi
  hide:
    - navigation.edit  # hides the edit button globally

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
