site_name: Process PI
site_url: https://processpi.org
repo_url: https://github.com/varma666/ProcessPi
repo_name: GitHub

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.copy
    - palette.toggle        # ensure light/dark toggle works
  palette:
    scheme: processpi        # your brand palette
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/logo.png

extra_css:
  - css/custom.css

nav:
  
  - Install:
      - Installation: installation.md
  - User Guide:
      - Introduction: user-guide/introduction.md
      - Features: user-guide/features.md
      - Examples: user-guide/examples.md
      - Units:
          - Length: user-guide/units/length.md
          - Pressure: user-guide/units/pressure.md
          - Temperature: user-guide/units/temperature.md
      - Components:
          - Overview: user-guide/components/components.md
          - Acetic Acid: user-guide/components/acetic_acid.md
          - Pumps: user-guide/components/pumps.md
          - Heat Exchangers: user-guide/components/heat-exchangers.md
          - Valves: user-guide/components/valves.md
          - Mixers: user-guide/components/mixers.md
          - Splitters: user-guide/components/splitters.md
  - API:
      - Overview: api_reference.md
      - Pipelines: user-guide/pipe-lines/pipelines.md
      - Heat Transfer: user-guide/calculations/calculations.md
      - Components: user-guide/components/components.md
  - Examples:
      - Pipeline Example: examples/pipeline-example.md
      - Heat Flux Example: examples/heatflux-example.md
      - Pump Example: examples/pump-example.md
  - Community:
      - Roadmap: about/roadmap.md
      - Contributing: about/contributing.md
      - License: about/license.md
      - Changelog: about/changelog.md
  - GitHub: https://github.com/varma666/ProcessPi

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/varma666/ProcessPi
  hide:
    - navigation.edit
  content:
    title: Cookie consent
    description: 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2025 ProcessPI
