site_name: ProcessPI
site_description: "Chemical Engineering Toolkit"
site_author: Raviteja Varma Nadimpalli
repo_url: https://github.com/varma666/ProcessPi
repo_name: ProcessPI
edit_uri: blob/main/docs/
site_url: https://varma666.github.io/ProcessPi/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: docs/overrides       # For template overrides (header/footer)
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    primary: 
      main: "#212366"
      text: "white"
    accent: 
      main: "#E46216"
      text: "white"
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  extra_css:
    - css/custom.css               # Custom CSS for spacing, footer, etc.

extra:
  footer: "Made with ❤️ towards Chemical Engineering"  # Tagline in footer

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
      - Units: usage/units.md
      - Components: usage/components.md
      - Pipelines & Networks: usage/pipelines.md
      - Calculations: usage/calculations.md
  - Roadmap: roadmap.md
  - API Reference: api_reference.md
  - Contributing: contributing.md
  - License: license.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
