site_name: Process PI
site_url: https://processpi.org
repo_url: https://github.com/varma666/ProcessPi
repo_name: GitHub

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    #- navigation.expand
    - navigation.tracking
    #- navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.copy
    - palette.toggle        # ensure light/dark toggle works
  palette:
    scheme: processpi        # your brand palette
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/logo.png

extra_css:
  - css/custom.css

nav:
  #- Home: index.md
  - Install:
      - Installation: installation.md
  - User Guide:
      - Introduction: user-guide/introduction.md
      - Features: user-guide/features.md

      - Units: 
          - Overview: user-guide/units/overview.md
          - Length: user-guide/units/length.md
          - Pressure: user-guide/units/pressure.md
          - Temperature: user-guide/units/temperature.md
          #- Time: user-guide/units/time.md
          - Mass: user-guide/units/mass.md
          - Volume: user-guide/units/volume.md
          - Flow Rate:
              - Volumetric Flow Rate: user-guide/units/volumetric_flowrate.md
              - Mass Flow Rate: user-guide/units/mass_flowrate.md
          - Density: user-guide/units/density.md
          - Viscosity: user-guide/units/viscosity.md
          - Area : user-guide/units/area.md
          - Diameter: user-guide/units/diameter.md
          - Dimensionless Numbers: user-guide/units/dimensionless.md
          - Heat Flow: user-guide/units/heat_flow.md
          - Heat Flux: user-guide/units/heat_flux.md
          - Heat Transfer Coefficient: user-guide/units/heat_transfer_coefficient.md
          - Heat Of Vaporization: user-guide/units/heat_of_vapouraization.md
          - Power: user-guide/units/power.md
          - Specific Heat: user-guide/units/specific_heat.md
          - String: user-guide/units/string.md
          - Thermal Conductivity: user-guide/units/thermal_conductivity.md
          - Thermal Resistance: user-guide/units/thermal_resistance.md
          - Velocity: user-guide/units/velocity.md
          
      - Components:
          - Overview: user-guide/components/components.md
          - Acetic Acid: user-guide/components/acetic_acid.md
          - Acetone: user-guide/components/acetone.md
          - Acrylic Acid: user-guide/components/acrylic_acid.md
          - Air : user-guide/components/air.md
          - Ammonia: user-guide/components/ammonia.md
          - Benzene: user-guide/components/benzene.md
          - Benzoic Acid: user-guide/components/benzoic_acid.md
          - Bromine: user-guide/components/bromine.md
          - Butane: user-guide/components/butane.md
          - Carbon Dioxide: user-guide/components/carbon_dioxide.md
          - Carbon Monoxide: user-guide/components/carbon_monoxide.md
          - Chlorine: user-guide/components/chlorine.md
          - Chloroform: user-guide/components/chloroform.md
          - Carbon Tetrachloride: user-guide/components/carbon_tetrachloride.md
          - Cyclohexene: user-guide/components/cyclohexene.md
          - Chloro Methane: user-guide/components/chloromethane.md
          - Cynogen: user-guide/components/cynogen.md
          - Ethane: user-guide/components/ethane.md
          - Ethanol: user-guide/components/ethanol.md
          - Ethylacetate: user-guide/components/ethylacetate.md
          - Gas: user-guide/components/gas.md
          - Inorganic Liquids: user-guide/components/inorganic_liquids.md
          - Methanol: user-guide/components/methanol.md
          - Oil: user-guide/components/oil.md
          - Organic Liquids: user-guide/components/organic_liquids.md
          - Steam: user-guide/components/steam.md
          - Toluene: user-guide/components/toluene.md
          - Vapor: user-guide/components/vapor.md
          - Water: user-guide/components/water.md
      - Calculations:
          - Overview: user-guide/calculations/calculations.md
          - Calculation Engine: user-guide/calculations/calculation_engine.md

  - Examples:
      - Overview: api_reference.md
      - Pipelines: examples/pipe-lines/pipelines.md
      - Calculations: examples/calculations/calculations.md
      - Components: examples/components/components.md
  - Community:
      - Roadmap: about/roadmap.md
      - Contributing: about/contributing.md
      - License: about/license.md
      - Changelog: about/changelog.md
  - GitHub: https://github.com/varma666/ProcessPi

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/varma666/ProcessPi
  hide:
    - navigation.edit
  content:
    title: Cookie consent
    description: 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2025 ProcessPI
