site_name: Process PI
site_url: https://processpi.org
repo_url: https://github.com/varma666/ProcessPi
repo_name: GitHub

theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - toc.integrate   # integrates toc into sidebar only inside docs
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Install:
      - Installation: getting-started/installation.md
  - User Guide:
      - Introduction: user-guide/introduction.md
      - Features: user-guide/features.md
      - Examples: user-guide/examples.md
      - Units:
          - Length: user-guide/units/length.md
          - Pressure: user-guide/units/pressure.md
          - Temperature: user-guide/units/temperature.md
  - API:
      - Overview: api/index.md
      - Pipelines: api/pipelines.md
      - Heat Transfer: api/heat-transfer.md
      - Mass Transfer: api/mass-transfer.md
      - Equipment: api/equipment.md
  - Examples:
      - Overview: examples/index.md
      - Pipeline Example: examples/pipeline-example.md
      - Heat Flux Example: examples/heatflux-example.md
      - Pump Example: examples/pump-example.md
  - Community:
      - Roadmap: about/roadmap.md
      - Contributing: about/contributing.md
      - License: about/license.md
      - Changelog: about/changelog.md
  - GitHub: https://github.com/varma666/ProcessPi
