name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'   # triggers when you create a version tag like v0.1.2

permissions:
  id-token: write   # required for Trusted Publishing
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Verify TestPyPI install
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://test.pypi.org/simple/ processpi --extra-index-url https://pypi.org/simple
          python -c "import processpi; print('✅ Version:', processpi.__version__)"

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Verify PyPI install
        run: |
          python -m pip install --upgrade pip
          pip install processpi --extra-index-url https://pypi.org/simple
          python -c "import processpi; print('✅ Version:', processpi.__version__)"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
