name: Publish Python 🐍 distributions 📦 to TestPyPI and PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Verify package
        run: twine check dist/*

      - name: Install package (with deps) for smoke test
        run: |
          pip install .[dev]
          python -c "import processpi; print('✅ Import successful!')"

  publish-testpypi:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Required for trusted publishing
    environment:
      name: testpypi
      url: https://test.pypi.org/p/processpi
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist
          verify-metadata: true
          attestations: false   # Disable attestations

      - name: Verify installation from TestPyPI
        run: |
          pip install --index-url https://test.pypi.org/simple/ --no-deps processpi
          python -c "import processpi; print('✅ TestPyPI package works!')"

  publish-pypi:
    runs-on: ubuntu-latest
    needs: publish-testpypi
    permissions:
      id-token: write  # Required for trusted publishing
    environment:
      name: pypi
      url: https://pypi.org/p/processpi
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          verify-metadata: true
          attestations: false   # Disable attestations

      - name: Verify installation from PyPI
        run: |
          pip install --upgrade processpi
          python -c "import processpi; print('✅ PyPI package works!')"
