name: Python package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: true  # Trusted Publishing mode

      - name: Verify TestPyPI install (with dependencies)
        run: |
          pip install --index-url https://test.pypi.org/simple/ --upgrade processpi
          python -c "import processpi; print('✅ TestPyPI version:', processpi.__version__)"

      - name: Publish to PyPI
        if: success()
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true  # Trusted Publishing mode
