name: Python package

on:
  push:
    tags:
      - 'v*'   # Runs when a version tag is pushed (e.g., v0.1.2.2)

permissions:
  contents: read
  id-token: write  # Required for OIDC Trusted Publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: |
          python -m build

      # ---- Publish to TestPyPI ----
      - name: Publish to TestPyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: true

      # ---- Install from TestPyPI to verify ----
      - name: Verify TestPyPI package install
        run: |
          pip install --index-url https://test.pypi.org/simple/ --no-deps processpi
          python -c "import processpi; print('Installed version:', processpi.__version__)"

      # ---- Publish to PyPI ----
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
