name: Publish Python 🐍 package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build, TestPyPI & PyPI Publish

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Upgrade pip & install build tools
      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Build the package
      - name: Build package
        run: python -m build

      # Publish to TestPyPI
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      # Sanity check install from TestPyPI with fallback to PyPI for dependencies
      - name: Install from TestPyPI and check version
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://test.pypi.org/simple/ \
                      --extra-index-url https://pypi.org/simple \
                      processpi --upgrade
          python -c "import processpi; print(f'✅ Installed version: {processpi.__version__}')"

      # Publish to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
